### ISSUE TITLE
Implement withFilter

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#145]

**Comment by pnf** [comment]
`withFilter` always seemed to me to be a weird special case.  I.e. why would one be concerned about creating a temporary collection when filtering but not anywhere else.  Now that we have very lightweight, iterator-based views, wouldn't most uses of `withFilter` be better rewritten `.view.filter....`?  I  suppose I'm also suggesting changing the semantics of `for` desugaring to use views as much as possible.

**Comment by Ichoran** [comment]
@pnf - `withFilter` is a special hint that the contents are ultimately likely to be consumed in full and traversed exactly once.  There are cases where this is very valuable information regarding performance.  Because `for` desugaring is _not_ specific to collections, it makes sense to retain this distinction (inasmuch as it ever did).  We can _implement_ `withFilter` as `.view.filter`, but we shouldn't use the collections rewrite as justification for removing `withFilter`.

**Comment by pnf** [comment]
I agree it's a hint that traversal will occur at most once, though I don't see how the probability of complete consumption figures. If anything, it's more valuable to avoid the intermediate when it won't be consumed.

I understand that we can't actually get rid of withFilter especially after the recent celebration over requiring it, but the for desugaring could be enhanced to make it easier to be fully lazy. Admittedly it requires type awareness, but @adriaanm's comment in scala/scala#5725 seems to imply there's some openness to extending for-desugaring past the parser stage. We could even do applicatives...

**Comment by julienrf** [comment]
BTW, do we need `FilterMonadic`? I’m tempted to say no but maybe it is useful to “mark” that a computation is supposed to be used in `for`.

**Comment by odersky** [comment]
@julienrf Out of hand, I don't see a need of `FilterMonadic`. 

Regarding `withFilter`, the following discussion is also relevant: https://github.com/lampepfl/dotty/issues/2573.

If we follow the recommendations there, it would be good to have an `empty` in each collection (not in the companion object; in the collection itself). If we have that we could change the scheme for for-expression translation and phase out `withFilter`. All that would happen over time though, right now we definitely need to leave `withFilter` in. So my remark is about adding `empty` now, so that we can remove `withFilter` later.
