### ISSUE TITLE
Make scala.Seq = strawman.collection.immutable.Seq

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#149]

**Comment by EPronovost** [comment]
Is this a step towards #179 ?

**Comment by szeiger** [comment]
Other non-immutable collection types in package object `scala`:

- `type IterableOnce[+A] = scala.collection.IterableOnce[A]`: New, replaces `TraversableOnce`, no immutable version

- `type Iterator[+A] = scala.collection.Iterator[A]`: Like `IterableOnce` this has no immutable version

- `type Iterable[+A] = scala.collection.Iterable[A]`: There is an `immutable.Iterable` but I suggest we keep this one as the lowest common denominator for abstracting over collection types.

- `type IndexedSeq[+A] = scala.collection.IndexedSeq[A]`: Since we're changing `Seq` we should also change `IndexedSeq`

- `type BufferedIterator[+A] = scala.collection.BufferedIterator[A]`: Why is this even here? `BufferedIterator` is not a very common type. I suggest deprecating the alias.

- `type StringBuilder = scala.collection.mutable.StringBuilder`: Probably quite common, I'd keep it for now

**Comment by Ichoran** [comment]
Incidentally, if we're going to add immutable iterators, now would be the time to do it.  They're annoying to use because the signature works out to be equivalent to

```
def advance: Option[(Immuterator[A], A)]
```

which imposes an additional burden of keeping track of the advanced state of the immutable iterator.

But since we're thinking about an enhanced immutable interface, I thought it was worth raising.

Note for those wondering about usage: immutable iterators are best consumed in tail-recursive methods, e.g.

```
def sum(ii: Immuterator[Int], accumulator: Int = 0) = ii.advance match {
  case Some((ij, n)) => sum(ij, accumulator + n)
  case None => accumulator
}
```

and similar constructs.

**Comment by SethTisue** [comment]
@szeiger agreed on all points

**Comment by julienrf** [comment]
@Ichoran what’s the advantage over pattern matching on `case head :: tail`?

**Comment by SethTisue** [comment]
could we move the immutable-iterator discussion to a new ticket?

**Comment by szeiger** [comment]
Further issues:

- Implicit conversions from `Array` to `Seq` are very common (at least in the compiler codebase). I'll add a deprecated even-lower-priority-than-WrappedArray conversion from `Array` to `immutable.IndexedSeq` that copies the array.

- Should `toSeq` and `toIndexedSeq` always return the immutable version? It would be nicer if `toSeq` actually gave you a `Seq` (and not just a `collection.Seq`). When used on an existing mutable collection they would have copy it anyway to avoid accidental sharing so it shouldn't be much of a performance issue.

**Comment by szeiger** [comment]
This "immutable iterator" looks like a Stream or LazyList to me, assuming `advance` doesn't really advance anything. If it does, it is no longer immutable, just a less efficient mutable iterator.

**Comment by Ichoran** [comment]
In brief: immutable iterators don't cache anything (unlike `LazyList`), and are a generalization of head-tail decomposition to collections where tail isn't terribly efficient.  But, yeah, if we wanted to do this we should talk about it on another ticket.

**Comment by sjrd** [comment]
I wholeheartedly agree with @dwijnand. Everything else in `Predef` is now immutable by default. We should keep `Iterable` immutable as well. When you write code that takes an `Iterable` in Scala, one would first assume that it is immutable. Handling possible mutations under one's feet is tricky, and should be explicit.

**Comment by julienrf** [comment]
Reopening because we might want to make `scala.Iterable[+A] = scala.collection.immutable.Iterable[A]` as well…

**Comment by dwijnand** [comment]
(given the description of this ticket, maybe it's better to create a new one to track that)

**Comment by julienrf** [comment]
@dwijnand done!
