### ISSUE TITLE
Add appendAll (:++), add (+) and addAll (++) operations

### ISSUE THREAD

**Issue by odd** [scala/collection-strawman#181]
With `prependAll` added we currently have the following membership affecting operations:
* `prepend` (aliased as `+:`)
* `append` (aliased as `:+`)
* `prependAll` (aliased as `++:`)
* `concat`(aliased as `++`)

For symmetry the following operations should be added:
* `appendAll` (aliased as `:++`)
* `add` (aliased as `+`)
* `addAll` (aliased as `++`, alias for `concat`)

Further, the operations `add`/`addAll`/`concat` could then be defined in `Iterable` (thus available for `Set`) as they do not entail any sequential positioning, while `prepend`/`prependAll`, `append`/`appendAll` could be defined in `Seq` since they do in fact entail sequential positioning (thus not avaliable for `Set`). For a specific `Seq` implementation `concat` could either be implemented as an alias for `prependAll` or `appendAll` depending on which is more efficient (e.g. the former for `List` and the latter for `ImmutableArray`).

**Comment by julienrf** [comment]
In `Set` collections we have `+` (and its alphabetic name is `incl` instead of `add` to not be confused with the `add` of the Java collections -- which mutates the collection in place). I don’t think we should have `+` on `Seq` collections.

I don’t think we should have different names for `++` (`concat`, `addAll`, `appendAll`). It could make sense to remove `++` on `Seq` collections and have only `:++` (`appendAll`) and `++:` (`prependAll`), by symmetry with `:+` and `+:` but that will require one more step for existing code bases to migrate to the strawman (specifically, replacing `++` with `:++`).

**Comment by odd** [comment]
I see your point regarding `add`/`addAll`. I still see a real value in having `appendAll` for `Seq` collections though. If removing `concat` from `Seq` as you described is considered a too big a change for ease-of-migration reasons, I believe adding `appendAll` (aliased to `:++`) while still keeping `concat` in `Seq`(thus having both methods available for `Seq` collections) is the best choice (i.e. symmetry and ease of discovery beats DRY in this case IMHO).

**Comment by Ichoran** [comment]
I agree.  Symmetry beats DRY.  But that is more true of `:++` than `appendAll`, I think.  `concat` is straightforward enough.

**Comment by julienrf** [comment]
Closed in #184.
