### ISSUE TITLE
Explore using CHAMP (Compressed Hash-Array Mapped Prefix-tree) instead of trees

### ISSUE THREAD

**Issue by mdedetrich** [scala/collection-strawman#192]
As per https://contributors.scala-lang.org/t/ongoing-work-on-standard-collections-redesign/293 and the paper https://michael.steindorfer.name/publications/phd-thesis-efficient-immutable-collections.pdf, there is newer way of implementing immutable data structures using compressed has arrays instead of trees.

The reason why CHAMP provides better performances is that it uses `Array` (which on the JVM is one of the few ways to control cache locality), so there ends up being a lot less cache misses compared to using a shallow tree (which is common implementation for immutable data structures such as `Vector` and `Map`)

Would it be realistic to explore using these techniques in the collections redesign? Seems like a good time to do so, and it would give Scala an edge over other languages since immutable collections are used so persuasively.

**Comment by Ichoran** [comment]
Yes, it's an appropriate time to try it out.  I'll do it eventually if no-one else gets to it first.

**Comment by mdedetrich** [comment]
The guy has already made some implementations in Java, you can see them here https://github.com/usethesource/capsule

**Comment by msteindorfer** [comment]
I prototyped a fully functional integration of CHAMP hash-sets for `collection-strawman`, which is available on a [separate branch of my `collection-strawman` fork](https://github.com/msteindorfer/collection-strawman/tree/capsule-integration).

In particular I'm reusing the inner trie structures of the [Capsule](https://github.com/usethesource/capsule) hash-set, with a rewritten outer collection layer in Scala. Capsule's data structures are designed for reuse, without the need for wrappers and delegators that add indirections or add memory overhead.

The two relevant (and only) source files that were added / changed are:
* [immutable.CapsuleHashSet.scala](https://github.com/msteindorfer/collection-strawman/blob/capsule-integration/src/main/scala/strawman/collection/immutable/CapsuleHashSet.scala)
* [immutable.Set.scala](https://github.com/msteindorfer/collection-strawman/blob/capsule-integration/src/main/scala/strawman/collection/immutable/Set.scala)

By the default the branch uses the current default `immutable.HashSet` implementation, however if at JVM startup time the system property `strawman.collection.immutable.useCapsule=true` is passed to the JVM, the `CapsuleHashSet` becomes the default set implementation. The flag can be added to the JVM with `java -Dstrawman.collection.immutable.useCapsule=true ...` or in SBT by modifying the `javaOptions`.

What's the effect? Let's look first at data structure sizes of `collection-strawman` compared to `Scala 2.12.3`:

```
./runStrawman.sh false

Benchmark          (size)  (valueFactoryFactory)         Score   Units

Set.footprint     1048576               VF_SCALA  44101544.000   bytes
Set.footprint     1048576      VF_SCALA_STRAWMAN  44101544.000   bytes
```

When we switch on Capsule we get the following:

```
./runStrawman.sh true

Benchmark.         (size)  (valueFactoryFactory)         Score   Units

Set.footprint     1048576               VF_SCALA  44101544.000   bytes
Set.footprint     1048576      VF_SCALA_STRAWMAN  24148136.000   bytes
```

Now let's look at execution time of individual operations (once again first comparing `collection-strawman` to `Scala 2.12.3`):

```
./runStrawman.sh false

Benchmark                    (size)  (valueFactoryFactory)            Score   Units

Set.timeLookup              1048576               VF_SCALA           26.173   ns/op
Set.timeLookup              1048576      VF_SCALA_STRAWMAN           26.699   ns/op

Set.timeInsert              1048576               VF_SCALA          111.062   ns/op
Set.timeInsert              1048576      VF_SCALA_STRAWMAN           87.274   ns/op

Set.timeRemove              1048576               VF_SCALA          109.167   ns/op
Set.timeRemove              1048576      VF_SCALA_STRAWMAN           87.821   ns/op

Set.timeIteration           1048576               VF_SCALA     25911669.188   ns/op
Set.timeIteration           1048576      VF_SCALA_STRAWMAN     55117882.747   ns/op

Set.timeEqualsWorstCase     1048576               VF_SCALA     43526887.466   ns/op
Set.timeEqualsWorstCase     1048576      VF_SCALA_STRAWMAN     96442527.855   ns/op
```

When we switch on Capsule we get the following:

```
./runStrawman.sh true

Benchmark                    (size)  (valueFactoryFactory)            Score   Units

Set.timeLookup              1048576               VF_SCALA           26.480   ns/op
Set.timeLookup              1048576      VF_SCALA_STRAWMAN           31.277   ns/op

Set.timeInsert              1048576               VF_SCALA          113.179   ns/op
Set.timeInsert              1048576      VF_SCALA_STRAWMAN          105.366   ns/op

Set.timeRemove              1048576               VF_SCALA          112.131   ns/op
Set.timeRemove              1048576      VF_SCALA_STRAWMAN          100.247   ns/op

Set.timeIteration           1048576               VF_SCALA     28014173.889   ns/op
Set.timeIteration           1048576      VF_SCALA_STRAWMAN     17009978.085   ns/op

Set.timeEqualsWorstCase     1048576               VF_SCALA     42943827.862   ns/op
Set.timeEqualsWorstCase     1048576      VF_SCALA_STRAWMAN     23383676.245   ns/op
```

To summarize some that little experiment: Capsule integration into `collection-strawman` improves footprint, iteration and equality checking performance by ~2x. In contrast, `collection-strawman` adds currently a ~2x performance regression over Scala 2.12.3 for iteration and equality checking, while keeping the exact same footprint. The performance of the basic operations is with Capsule typically slightly behind `collection-strawman`, but faster than Scala 2.12.3. 

Where to go from here? The whole experiment was setup to get an intuition of possible gains / losses of the CHAMP design in `collection-strawman` without heavily investing in reimplementation upfront. The integration of Capsule in `collection-strawman` now enables other non-microbenchmarks (e.g., scalac) to evaluate the suitability of various CHAMP designs / implementations.

If experimentation shows that it's definitely worth to switch to CHAMP, there are two options that I see:
* lightweight approach: use a Capsule integration similar as prototyped above. Advantage: little effort, but high gains. Disadvantage: dependency on a Java library.
* heavyweight approach: reimplement CHAMP in `collection-strawman`. Advantage: native Scala implementation that can evolve separately. Disadvantage: high engineering effort. (I already evaluated implementation options and would choice a slightly different design than currently prototyped with the Capsule integration.)

I am also done with a benchmarking setup that extensively compares `collection-strawman` to Scala 2.12.3 and the most important persistent collection libraries available on the JVM, in order to judge `collection-strawman`'s performance w.r.t. the competition. The benchmarks cover many more operations. They also uncovered more performance regressions introduced in `collection-strawman` compared to Scala 2.12.3. I'll report on the benchmarking setup and results in a more suitable / general place than this specific issue about CHAMP.

(CC/ @julienrf @szeiger @retronym)

**Comment by DarkDimius** [comment]
@mdedetrich does CapsuleSet support Scala cooperative equality? Otherwise to Scala collection will be skewed.

**Comment by DarkDimius** [comment]
The last time I did my own Capsule benchmarks most of the performance wins for small collections were due to absence of cooperative equality. The speedup due to better memory layout was only visible for collections of more than 10 000 elements.

**Comment by msteindorfer** [comment]
@DarkDimius can you pinpoint me to an API specification or a document of what cooperative equality is and when it kicks in?

The current integration in strawman in very simple and also quick to review. In principle it should support everything the strawman HashSet does.

I am not sure if this has something to do with cooperative equality (waiting for more info), but Capsule's data structures can take a custom (java.util) comparator for equality checking. This feature is heavily used in its integration in the Rascal language, which has a different equality semantic and API than Java.

**Comment by msteindorfer** [comment]
@DarkDimius thanks for giving me nutshell overview. If you by chance get hold of the specification document for cooperative equality, please send me the link to that as well. I had a look at the `BoxesRunTime.java` implementation you sent me.

> [...] double(0), float(0), int(0), char(0), byte(0) and even bigDecimal(0) and bigNumeric(0) have the same hashcode and will be equal. This requires intercepting calls if two expressions being compared have types that are not bounded by AnyRef. This is done automatically by compiler.

I've myself experience with implementing cooperative equality in other JVM languages, and in my opinion the goal cannot be achieved solely by the compiler intercepting comparisons of comparable expressions. In essence you would void anything that relies a [hashCode/equals contract](http://docs.oracle.com/javase/8/docs/api//java/lang/Object.html#hashCode--). E.g., when using a potential heterogeneous hash-set the compiler has no means to intercepts calls to hashCode/equals. Because the hash codes of primitive types differ ...
```
scala> 2.0.hashCode
res2: Int = 1073741824

scala> 2.hashCode
res3: Int = 2
```
... using a hash data structure such as hash-trie would store both elements in different positions in the tree. To support cooperative equality in all circumstance, you'd often have to fall back to slow-path comparisons, giving up performance. The issue is more involved, because cooperative equality taints whole object graphs (by not adhering to hashCode/equals contract), it voids functional optimizations such as hash-consing and memoization as well. In the past I worked on a performance profiler to pinpoint such problems (cf. paper [Performance Profiling of Maximal Sharing](http://dl.acm.org/citation.cfm?id=2851566&CFID=795577762&CFTOKEN=27784861)).

Some of my concerns and comments may not map directly apply to the Scala case, because I don't know the specification of the proposal. (Sending me the proposal could bring us on the same line.)

> Could you rerun benchmarks with it as a comparator and also include AnyRefMap in your comparison?

I'll try to allocate some time for doing both extensions. Once I'm done, I'll report the updated results.

**Comment by mdedetrich** [comment]
I also believe that a Scala implementation would be beneficial as it would be easier to port for the scala.js and scala-native platforms (I also have an untested suspicion that a CHAMP implementing on scala.js could be faster if it uses Javascript native arrays)

**Comment by sjrd** [comment]
@msteindorfer Scala's cooperative equality implementation includes a cooperative hash code:
```
scala> 2.0.##
res0: Int = 2

scala> 2.##
res1: Int = 2
```
The `hashCode`/`equals` contract of Java/JVM is preserved in Scala. But there is also a different contract for `##`/`==`. Scala collections need to consistently use `==` and `##` on their elements to support cooperative equality.

**Comment by msteindorfer** [comment]
@sjrd thanks for pointing out the cooperative hash code a.k.a. `##`. So if I understand you correctly, Scala has two pairs of hash code and equality operations, where each pair forms a `hashCode`/`equals` contract? Which are the exact operations that are paired up? I assume `hashCode` with `==`, and `##` with `BoxesRuntime.equals` (as @DarkDimius pointed out)?

> E.g., when using a potential heterogeneous hash-set the compiler has no means to intercepts calls to hashCode/equals [...]

How does Scala support the use-case I was describing above? What I got from your answer is that a call to the cooperative equality comparator must consistently call the same operator on every nested object, right?

That would imply that a cooperative equality check for two hash-sets would result in something similar to (... sorry for the Java streams syntax): 
```
set1.size == set2.size && set1.stream().allMatch(set2::containsCoopeartive);
```
The crucial part there is that instead of a regular `contains` lookups that perform in O(1) on a hash-set, an alternative `containsCoopeartive` has to be invoked that relies on linear scanning (unless you rehash the whole set with the cooperative hash code before doing the equality check).

**Comment by sjrd** [comment]
> So if I understand you correctly, Scala has two pairs of hash code and equality operations, where each pair forms a hashCode/equals contract? Which are the exact operations that are paired up? I assume hashCode with ==, and ## with BoxesRuntime.equals

No. `==` is paired with `##`, and `equals` is paired with `hashCode`. In practice, in Scala code, no one every calls `equals` nor `hashCode` unless they know what they're doing. Everyone just calls `==` and `##`, which implement Scala's cooperative equality.

`BoxesRunTime.equals` is never called directly in user code either, even by people who know what they're doing (the Scala compiler rewrites `a == b` into `BoxesRunTime.equals(a, b)`, but as a Scala dev you don't need to know that).

> How does Scala support the use-case I was describing above?

Because all Scala data structures already recursively call `==` and `##` on their nested objects. So the heterogeneous collections just need to call `==` and `##` on their elements, period.

**Comment by msteindorfer** [comment]
Thanks for the description of the pairing and the how cooperative equality works under the hood. My question was coming from he mindset of compiler writer and core library engineer, thus, I didn't assume that operations such as `BoxesRunTime.equals(a, b)` are called by Scala users themselves.

**Comment by msteindorfer** [comment]
@DarkDimius, I can confirm that the previous measurements of `timeEqualsWorstCase` did not take cooperative equality into account. As suggested, I adopted the implementation to make use of the `BoxesRunTime.equals` comparators. Here's the revised code:

```
override def equals(that: Any): Boolean =
  that match {
    case set: HashTrieSet[A] =>
      (this eq set) ||
        (size == set.size) && (rootNode.equivalent(set.rootNode,
          (x: scala.AnyRef, y: scala.AnyRef) => (x eq y) || BoxesRunTime.equals2(x, y)))
    case _ => super.equals(that)
  }
```

After implementing support for cooperative equality, I can confirm the re-executing the benchmarks yields results consistent with what I reported before:

```
./runStrawman.sh true

Benchmark                   (size)  (valueFactoryFactory)           Score  Units
Set.timeEqualsWorstCase          8      VF_SCALA_STRAWMAN          37.636  ns/op
Set.timeEqualsWorstCase          8               VF_SCALA          83.815  ns/op

Set.timeEqualsWorstCase       2048      VF_SCALA_STRAWMAN       26555.928  ns/op
Set.timeEqualsWorstCase       2048               VF_SCALA       49269.496  ns/op

Set.timeEqualsWorstCase    1048576      VF_SCALA_STRAWMAN    24516202.274  ns/op
Set.timeEqualsWorstCase    1048576               VF_SCALA    42337816.017  ns/op
```

Improvements of 2x are visible from tiny collections onwards.

**Comment by julienrf** [comment]
Hi @msteindorfer! What’s the status of this work? The numbers look promising! I think we should replace our `HashMap` and `HashSet` with your implementations. Are working on a 100% Scala implementation? We need that in order to be support non-JVM runtimes.

**Comment by msteindorfer** [comment]
Hi @julienrf, I didn't work on this issue recently. However, I plan to allocate time from November onwards to provide 100% Scala implementations of `HashMap` and `HashSet` as you suggested.

Were there any attempts made to test my integration for other benchmark scenarios or workloads?

**Comment by julienrf** [comment]
Not that I know. By the way, is the source code of your benchmarks available somewhere?
