### ISSUE TITLE
Override methods of LazyList for GC friendliness

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#197]
Most of the methods of the current `Stream` collection override the base methods for laziness, stack-safety and GC-friendliness.

In the strawman, `Iterable` operations are (mostly) lazy friendly, however they might not be GC friendly. We should check that. (E.g. methods `splitAt`, `take`, etc.)

**Comment by SethTisue** [comment]
I've found that `dropWhile` was stack safe in the old collections but not in the new:

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).

scala> Iterator.iterate(Stream.from(0))(_.dropWhile(_ => false)).drop(10000).next
res2: scala.collection.immutable.Stream[Int] = Stream(0, ?)
```

```
Welcome to Scala 2.13.0-pre-abf21b9 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).

scala> Iterator.iterate(Stream.from(0))(_.dropWhile(_ => false)).drop(10000).next
warning: there was one deprecation warning (since 2.13.0); for details, enable `:setting -deprecation' or `:replay -deprecation'
java.lang.StackOverflowError
  at scala.collection.immutable.LazyListFactory.$anonfun$from$2(LazyList.scala:502)
  at scala.collection.immutable.Stream$Cons.tail$lzycompute(LazyList.scala:732)
  at scala.collection.immutable.Stream$Cons.tail(LazyList.scala:730)
  at scala.collection.immutable.Stream$Cons.tail(LazyList.scala:727)
  at scala.collection.LinearSeqOps$$anon$1.next(LinearSeq.scala:27)
  at scala.collection.Iterator$$anon$12.next(Iterator.scala:572)
  at scala.collection.immutable.Stream$.evaluatedElem$lzycompute$2(LazyList.scala:808)
  at scala.collection.immutable.Stream$.evaluatedElem$2(LazyList.scala:808)
  at scala.collection.immutable.Stream$.fromIterator(LazyList.scala:809)
  at scala.collection.immutable.Stream$.$anonfun$fromIterator$3(LazyList.scala:809)
  at scala.collection.immutable.Stream$Cons.tail$lzycompute(LazyList.scala:732)
  at scala.collection.immutable.Stream$Cons.tail(LazyList.scala:730)
  at scala.collection.immutable.Stream$Cons.tail(LazyList.scala:727)
  at scala.collection.LinearSeqOps$$anon$1.next(LinearSeq.scala:27)
  at scala.collection.Iterator$$anon$12.next(Iterator.scala:572)
  at scala.collection.immutable.Stream$.evaluatedElem$lzycompute$2(LazyList.scala:808)
  at scala.collection.immutable.Stream$.evaluatedElem$2(LazyList.scala:808)
  at scala.collection.immutable.Stream$.fromIterator(LazyList.scala:809)
  ...
```

**Comment by NthPortal** [comment]
@SethTisue I think that probably deserves its own issue. From a brief look, I think it's a more general problem with nested views (especially since `Stream` is itself lazy). Definitely something which requires looking into on its own, aside from GC friendliness.

**Comment by SethTisue** [comment]
well this also overflows the stack:

```
Iterator.iterate(List(0).view: collection.View[Int])(_.dropWhile(_ => false)).drop(10000).next.head
```

but that doesn't particularly bother me, it seems acceptable to me that layering views like this would consume stack.

what about `Stream.dropWhile`?

it seems to me that `Stream.dropWhile` consuming stack is a regression. because `Stream` is strict in the head, and `dropWhile` returns a new `Stream`, `dropWhile` must evaluate and discard elements until it finds the result of the head. so it has no excuse for consuming stack. what the importance level of the regression is, is hard to say.

what about `LazyList.dropWhile`? I guess it makes sense that if the head hasn't been evaluated yet, the operation would be suspended and thus consume stack.

if the head *has* been evaluated, wouldn't it be nice if it were discarded, and that stack would only be consumed once we hit a non-evaluated head? but again, how important is this?

**Comment by SethTisue** [comment]
let me put this on a more concrete plane by showing you the code where I'm hitting this. I'm using `Stream` to implement a memoized cache of composite numbers and their factorizations:

```
  var stream = Stream.from(2).filter(!isPrime(_)).map(n => (n, factorizations(n)))
```

but I don't want the cache to just grow and grow; as I iterate, I sometimes know that I'm done with some initial segment of the cache. so at those points I do:

```
stream = stream.dropWhile(_._1 < k)
```

keeping the cache from growing indefinitely isn't only about reclaiming memory (GC-friendliness); it's also about speed, since I can only traverse the cache from the head, so if I don't discard the parts I'm done with, I'm going to end up with an O(n<sup>2</sup>) runtime, since I'll constantly be re-traversing the cache from the start.

**Comment by SethTisue** [comment]
`dropWhile` and `takeWhile` (as well as `drop` and `take`) are interesting operations because they have finite lifetimes. if I `map` or `filter` a stream or lazy list, the function passed needs to be retained indefinitely as part of the returned collection, since no matter how long the list is, we'll need to keep mapping and filtering it.

but once `dropWhile` has found the first counterexample, it's done. so perhaps it would fix my code to insert

```scala
stream.head: Unit
```

to force evaluation of the `dropWhile` to conclude.

the side effect (writing `stream.head` and discarding the value) is ugly (my example code uses `var` but that's inessential, it could just as well be done with parameter-passing), but to avoid that we could add a `forceOne` (`forceHead`?) operation to `LazyList` that returns `this.type`, just like `force` does.

okay, so I tried it and I still overflow the stack. so that seems like a bug to me. I'm out of time for this round of thinking out loud, but I'll come back to this and see if I think that we have incorrectly implemented `dropWhile` and friends.

thanks for listening.

**Comment by SethTisue** [comment]
oh one more thing: when I look at `LazyList`, I see `filterImpl` has:

```
  private[immutable] def filterImpl(p: A => Boolean, isFlipped: Boolean): C = {
    // optimization: drop leading prefix of elems for which f returns false
    // var rest = this dropWhile (!p(_)) - forget DRY principle - GC can't collect otherwise
    var rest: CC[A] = coll
...
```

so it looks to me like `dropWhile` and friends just need the same optimization.

**Comment by som-snytt** [comment]
@SethTisue wasn't there a puzzler in high school physics class about what it would take to get a "concrete plane" off the ground? Re: putting things on a more concrete plane.

**Comment by SethTisue** [comment]
@som-snytt maybe if Howard Hughes hadn't had Kleenex boxes on his feet he'd have gone that route instead of spruce

**Comment by NthPortal** [comment]
Should it be overridden in `LazyList` or `LazyListOps`?

**Comment by NthPortal** [comment]
> so it looks to me like `dropWhile` and friends just need similar overrides?

It's not obvious to me which friends these are. I don't think `take` or `takeWhile` can be overridden in a meaningful way without losing laziness, and I think `drop` (inherited from `LinearSeqOps`) should be fine already.

Also, upon looking at it, it's not clear to me why `drop` is overridden in `LinearSeqOps`, but `dropWhile` is not. Should this fix be moved up the inheritance hierarchy to `LinearSeqOps`?

**Comment by javax-swing** [comment]
From what i can tell it's not actually dropWhile but the fact that Stream/LazyList uses the iterator from LinearSeqOps which forces evaluation of the tail on calling next.

> 
  def iterator() = new Iterator[A] {
    private[this] var current: Iterable[A] = toIterable
    def hasNext = !current.isEmpty
    def next() = { val r = current.head; current = current.tail; r }
  }

by forcing the tail, next is being called again which forces the tail on the next element and so on

Please correct me if i'm mistaken :)

**Comment by javax-swing** [comment]
I believe this is only an issue with Stream as it's not lazy in the head. A quick fix would be a custom iterator that lazily invokes the tail.

```
class LazyIterator(var iterable: LinearSeq[A]) extends Iterator[A]
{
  var current: () => LinearSeq[A] = () => iterable
   def hasNext() : Boolean = {
      !current().isEmpty
   }

   def next() : A = {
     val c = current() // find the current value
     val r = c.head // the head is the value to return 
     lazy val nextIter = c.tail // lazily the tail is the next value to return
     current = () => nextIter // current is the nextIter
     r
   }
}
```

**Comment by NthPortal** [comment]
@javax-swing that may solve that particular snippet, but it doesn't solve the underlying problem. The problem is that each time you call `dropWhile`, you wrap the `Stream` in `Stream.fromSpecificIterable(View.DropWhile(this))`. Laziness of `head` doesn't really affect blowing the stack, just when it happens.

**Comment by javax-swing** [comment]
@NthPortal thanks for looking. thinking about it now I'm not sure that I'm correct. you make a good point that the Stream is wrapped on each call, it's possible the laziness in the head merely hides the problem at that point. I wonder what would happen when calling `next.head`  or `next.tail.head` with a `LazyList`?  as this would force the value from all the nested Streams (maybe). in any case it makes sense for drop etc on immutable linear sequences to re-use elements of the collection rather than copy. sorry for the ramblings, I just found this an interesting issue 😀
