### ISSUE TITLE
Build from dynamic type

### ISSUE THREAD

**Issue by szeiger** [scala/collection-strawman#198]
Removing the `BuildFrom` implicits in #168 (see https://github.com/scala/collection-strawman/pull/168/files#r129011332) breaks building based on the dynamic type of the source collection. The new `CanBuild` implicits are not an adequate replacement for this.

**Comment by julienrf** [comment]
It’s not clear to me what’s the difference is. Can you show me an example of situation where it behaves differently?

**Comment by julienrf** [comment]
Hmm, maybe I got it:

~~~ scala
val list = 1 :: 2 :: 3 :: Nil
val seq: Seq[Int] = list
val maybeSeq = optionSequence(seq.map(Some(_)))
println(maybeSeq) // prints “Some(Vector(1, 2, 3))” whereas with the previous code it printed “Some(List(1, 2, 3))”
~~~

**Comment by julienrf** [comment]
In #168 I removed the implicit because they were ambiguous with the ones defined in the factory objects. I’m not sure we can arrange the priorities because they come from different companion objects (`BuildFrom` versus the factory objects themselves).

If we can not fix the priorities then we have to make a choice between the two features: static-type directed factories versus runtime-type directed factories.

**Comment by szeiger** [comment]
Basically #168 removed `BuildFrom`. The type is still there and used at the call sites but all implicit instances of `BuildFrom` are actually `CanBuild`, which drops the "from" part. You're not only adding type-driven building but also removing value-driven building.

I did not find a way to resolve the ambiguities when I tried to implement it last time. I think the right way forward is to restore the old `BuildFrom` implicits and implement a type-driven version (`BuildTo`?) that is *not* a subtype of `BuildFrom` but convertible to `CanBuild`. This should avoid ambiguities, possibly at the cost of an explicit call to convert from `BuildTo` to `BuildFrom`, but maybe this one would work as an implicit conversion without being ambiguous.
