### ISSUE TITLE
Abstracting over arity for collect

### ISSUE THREAD

**Issue by tkroman** [scala/collection-strawman#235]
Well, not really abstracting, just providing a bunch of methods to do something similar to what collect does, but for multiple possible outcomes: https://scastie.scala-lang.org/z1M26e9CR8aE9RScaalVZw

Intended use-case: partitioning and unwrapping `Either`, `Try` & sealed hierarchies in a single pass.

**Comment by julienrf** [comment]
I wouldn’t use `collect` as a name in your case because you really want your partitioning function to be total (not partial).

Let’s name it `mapSplit3` (in reference to [that mapSplit](https://github.com/scala/collection-strawman/blob/9a7d85a3df176ccca47a630f985edd15ce0eece7/src/test/scala/strawman/collection/test/TraverseTest.scala#L114-L121)):

~~~ scala
val (ys1, ys2, ys3) =
  List(Foo(1), Bar("s"), Baz(Instant.now())).mapSplit3 {
    case Foo(x) => Left(x)
    case Bar(s) => Right(Left(s))
    case Baz(i) => Right(Right(i))
  }
~~~

Where `mapSplit3` would be defined like so:

~~~ scala
trait IterableOps[A, CC[_], C] {
  def mapSplit3[A1, A2, A3](f: A => Either[A1, Either[A2, A3]]): (CC[A1], CC[A2], CC[A3])
}
~~~

We could have `mapSplit4` as well, and so on… So, how could we define a generic `mapSplitN`? I guess its type signature would something along those lines:

~~~ scala
def mapSplitN[An](f: A => An)(implicit split: Split[An]): split.Out
~~~

And the `Split` implicit instance would be inductively built according to the `An` type so that if `An` matches `Either[A1, A2]` it would produce a `type Out = (CC[A1], C[A2])`, if `An` matches `Either[A1, Either[A2, A3]]` it would produce a `type Out = (CC[A1], CC[A2], CC[A3])`, and so on.

This is definitely an interesting programming challenge but I’m afraid that’s a too advanced use case to be part of the standard library.

**Comment by tkroman** [comment]
@julienrf I see. Is there a place for just a couple of ad-hoc implementations for `Try` & `Either`, which would anyway be the reason to have this sort of operation?

**Comment by tkroman** [comment]
I've seen a number of in-house implementations like `partitionEither`/`partitionTry`, which do exactly this. And I think I've seen a couple of people on Twitter talking about this, and everyone knows that Twitter rants are the real deal :D

**Comment by lihaoyi** [comment]
I'd love to have this in the standard library

**Comment by hochgi** [comment]
Very usefull. Would love to see it in std lib.
I usually know this as `partitionWith`:
https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/PartitionWith.scala
https://gist.github.com/hochgi/c8ee3273034fff8958d306459072fb22#file-partitionwith-scala

**Comment by julienrf** [comment]
@LPTK You can issue a PR, yes.
