### ISSUE TITLE
3.10.2017 Meeting

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#254]
- Merge `ArraySeq` (#52)? Replace `ImmutableArray`?
- Status of collections-laws
- Status of scala-library
- Equality on `View`: should `xs == ys` consume the elements of `ys` if `ys` is a `View`? (I think it should not, but currently this is the case with `IndexedView`, which inherits `equals` from `SeqOps`)
- Implicit conversion of companion objects to `BuildFrom`
- Benchmarking

**Comment by odd** [comment]
Hi, while I'm excited to see `ArraySeq` on the agenda, I feel that the question of replacing `Vector` should be answered in the negative since there are a number of benchmarks (in which a single position is affected) where `Vector` vastly outperforms `ArraySeq` (mainly `updated` and repeated `prepend`/`append` operations). 

If any of the collections in the strawman should be replaced with `ArraySeq` I believe it is `ImmutableArray` since `ArraySeq` outperforms (or matches) it in every benchmark.

**Comment by julienrf** [comment]
You’re right, I’ve updated the description!

**Comment by julienrf** [comment]
Here are some notes of the meeting:

- `ArraySeq` seems to be an excellent candidate for the default `IndexedSeq` but we are not sure we want to replace `ImmutableArray` nor `Vector` with it, because those collections could be useful in some situations too. On the other hand, I don’t think it’s good to have 3 implementations of `IndexedSeq` in the core…
- Status of the migration to scala/scala: scala-library does compile with the strawman, scala-reflect is on its way to compile and then the next step would be to have the compiler itself compile with the strawman.
