### ISSUE TITLE
Decide whether we want to support Java collections more directly

### ISSUE THREAD

**Issue by odersky** [scala/collection-strawman#283]
Following up on Reynold Xin's Scala Symposium keynote, I was talking with him about issues they had with Scala in Spark. One of the things he explained in detail was the problem of defining an API that worked equally well for Java and for Scala. They tried having separate APIs but gave up on it, because inconsistencies would creep in.

The main problem is that Scala collections and Java collections are different. So they would define overloaded methods that took either Scala collections or Java collections as parameters. As to the result type, they use `Array` everywhere because that's the only type that is shared between the two. Everyone agrees this is terrible. Is there something we should do about it in the collections redesign? On the Scala side, we have converters to adapt to Java collections, but these do not work for Java code. 

So, should we instead make Scala collections subtypes of Java collections? E.g.

 - scala.Iterator extends java.util.Iterator
 - scala.Iterable extends java.util.Iterable (or maybe java.util.Collection)?
 - scala.Seq extends java.util.List
 - scala.Map extends java.util.Map
 - scala.List extends java.util.Set

The mutation methods of these interfaces would have to throw `UnsupportedOperationException`s when implemented by immutable collections.

The advantage I see is that we would have a much easier way to define Scala libraries so that they are consumable from Java. Possible disadvantages are

 - more collection operations
 - possible name clashes
 - some loss of type safety when we expose a mutable operation that might not be implemented
 - more essential Java classes to implement on non-JVM platforms.

What do people think? 

/cc @Ichoran @adriaanm

**Comment by sjrd** [comment]
Big :-1: from me.

> some loss of type safety when we expose a mutable operation that might not be implemented

That kills it for me.
Also even `mutable.Seq` is not a `java.util.List`. You need `mutable.Buffer`.

> possible name clashes

`Map.get` comes to mind: returns `Option[V]` in Scala but nullable `V` in Java.

> more essential Java classes to implement on non-JVM platforms.

This is more a problem of *code size* than about reimplementation. They have been reimplemented already anyway. But in most Scala.js program, Java collections would not be pulled in after DCE. Now they would, and that would not be good at all.

Another problem: Scala collections and Java collections disagree on what equality means, so the inheritance is not even LSP-valid.

Another one: `java.util.List` has a method `listIterator()` which returns something that can move in the list *in both directions* in O(1). This cannot be implemented for all `Seq`s (e.g., Scala's `List`).

**Comment by odersky** [comment]
@sjrd It's surely not easy or pretty to do this, and some of the parts might not work at all (e.g. the problem with `Map.get` you mention might mean we can't subtype `java.util.Map`). But what's the alternative? Forget about APIs that can be consumed by Scala and Java alike?

**Comment by sjrd** [comment]
> Forget about APIs that can be consumed by Scala and Java alike?

Scala has apparently been able to thrive as is for years, so yes, maybe.

**Comment by odersky** [comment]
One possible way to get back some sort of type-safety is to mark methods with a new annotation such as `@javaOnly`. Then warn whenever these methods are used from Scala code. Maybe that's crazy, I am just brainstorming here.

**Comment by Milyardo** [comment]
The root problem I think is that current collections are unusable from Java. If even a reasonable subset of operations were usable in Java, there'd be much less pressure to support two APIs.

**Comment by odersky** [comment]
@Milyardo 

> The root problem I think is that current collections are unusable from Java. If even a reasonable subset of operations were usable in Java, there'd be much less pressure to support two APIs.

I believe some progress was already made in this respect, because strawman collections don't need implicit CanBuildFrom anymore. So operations like `map` and `flatMap` should now be accessible from Java.

**Comment by Ichoran** [comment]
I agree with @sjrd that the downsides are not worth it (especially the unsafe operations).

If we need a solution, I would prefer a @javaCollections type annotation that works like @BeanProperty except instead of generating the `get`, `set` pair, it would generate methods that take Java collections (by wrapping them and passing them on to the Scala implementation).  It should be able to get most SAMs as well.  (Possibly by manually overloading more than once with different SAM types when e.g. return type is abstracted in Scala but not Java.)

I don't think that this is going to help Spark out very much, though.  For a good deal of their stuff, they need arrays for performance, not just Scala/Java compatibility.

**Comment by odersky** [comment]
@Ichoran I don't think a @javacollections style annotation would work. Take filter, for example. We already have

    def filter(p: A => Boolean): scala.collection.Iterable[A]

We cannot add an overloaded version

    def filter(p: A => Boolean): java.util.Iterable[A]

That would constitute a double definition. And besides, you'd get overloading ambiguities when calling filter without an expected type.

**Comment by Ichoran** [comment]
@odersky - I was thinking of the case where the argument is a Scala collection, as that is the more difficult one when writing Java.  For return types, we could make first-class `asJava` methods on the collections to translate to the nearest Java version, if the compatibility layer that already exists is deemed too awkward.  Interface compatibility then wouldn't be seamless, but it would be close.

Also, we actually _could_ add the overloaded version in some cases if we translate functions to SAMs as well, because it would be `def filter(p: java.util.function.Predicate[A]): java.util.Iterable[A]`.

More radically, we could mangle the name of the Scala version, allowing both versions to coexist.  Scalac would then preferentially use its own version (or perhaps would _only_ use its own version absent an annotation or something to use the other).

Still, on further reflection, there may be too many warts for it to be worth it; if the behavior isn't easily intuitively predictable, it still may be to be best practice to define the Java interface by hand.

**Comment by ritschwumm** [comment]
baking in a dependency on java collections into scala.* sounds like a bad idea to me for a couple of reasons.

first, there's two kinds of scala programmers:

A) some only use scala as a better java, need support for "native" java libraries, and out of habit use mutable collections in many places. my feeling is their percentage is declining.

B) then there's the other kind: people who prefer pure scala libraries (which commonly are of a much higher quality), Option instead of null, Either instead of Exceptions, immutable collections instead of mutable ones, and so on. if they have to use a java library, it will be wrapped in some more "sane" interface. my impression is _their_ percentage is increasing.

if you let scala.* implement java collections, _all_ collections, ever the immutable ones aquire dependencies on (possibly fragile) base classes and additional complexity. while the added value might be worth the cost for group A, it definitely is not for group B who gains nothing - but still has to pay the cost.

second, i at least in some distant future, scala.Seq and friends should not exist at all.
mutable and immutable collections are different enough that usually it don't make any sens to
program against them: with e.q. a scala.Seq you neither have the performance advantage of
mutable collections, not the safety guarantees of immutable collections.

so, if those traits have to exist, at least keep them as lightweight as possible.

on a side note, as a member of group B, more or less the only thing i ever do with java collections is converting them to and from immutable scala collections.

**Comment by jroper** [comment]
On making it easier to create APIs that can be consumed both by Java and Scala. I spend a lot of time maintaining libraries and frameworks that seek to provide both first class Scala and Java support, and so here's my 2 cents:

In Lagom, we have completely separated APIs, they don't even exist on the classpath together. There is a certain overhead to doing this, yes, but personally I haven't found it too high, we have comprehensive test suites that test both APIs and stringent code reviews that don't allow feature parity to be lost. And I'm happy to accept that overhead, afterall, I am a library maintainer, I'm supposed to feel the pain of things like duplication so that the end developer doesn't have to, that's a large part of the point of libraries, to do the common and repetitive things so that end developers can have a great developer experience. I firmly believe that we should be optimising Scala for the end developer experience, not for library maintainer experience. That doesn't mean we ignore the library maintainer experience, but it does mean we shouldn't make improvements for library maintainers that are to the detriment of the end developers experience.

So, will having the Scala types extend Java types be a detriment to the end developer experience? I don't have a hugely strong opinion here, though methods like Map.get are a good example of where it might. And exposing the mutable methods isn't just about type safety (though that is a big problem since it can lead to the same types of bugs that you get in Java when using immutable implementations, where in unit tests you might happen to use a mutable type, and everything works, but then in production an immutable type is passed and it explodes). It's also about guiding new developers, when they Ctrl+space in their IDE to see what methods are available, having the mutable methods there are going to be a distraction and I think will inhibit their experience in making the shift from mutable to immutable types - they'll find themselves using the mutating methods when writing the code, and then when they run tests (minutes, hours, days later), they find that they have to rewrite their code and potentially change the design of their system.

Some other things to consider - collections aren't the only place where you have this issue - options, futures, tuples, partial functions, implicits/type classes, abstract types, where using the same API for both Java and Scala means you either have many, many overloads and need to come up with awkward naming strategies to distinguish return types, or you have to provide a sub optimal experience for one or both of the languages, for example, you might decide to use a case class instead of a tuple where really, a tuple is much more idiomatic in Scala. From what I've seen, usually you end up with both - both a suboptimal experience for both Java and Scala and a very messy API. So, making Scala collections extend Java collection types doesn't solve the problem that is seeking to be solved there, it only solves a small part of the problem, and other parts of the problem are intrinsically unsolvable.

I would recommend other libraries, particularly something like Spark which is meant to have a great developer experience especially for newbies, to do the same. There is an overhead, but it's not a big one, and having the library maintainer pay it means it's paid by the right developer at the right time.

**Comment by jroper** [comment]
Another big reason not to do this that I just thought of is future proofing.

While we can come up with solutions for name clashes that exist now, can we prevent name clashes that might happen in future? What happens if in a future JDK release, methods are added to the collections API that conflict with methods that the Scala API has now? What if a `tail` method is added that returns an incompatible type to what `Seq.tail` returns? What if `filter`, `map` and `flatMap` are added? Sure, they will have different binary signatures due to taking different functional interfaces, but usages of them will fail to typecheck at least in Java because you'll have an ambiguous method error because both methods will accept a functional interface that matches the lambda types, with neither being more specific than the other. I think we'll be setting ourselves up for big incompatibilities with future JDK versions if we go down this path.

**Comment by rxin** [comment]
@jroper We've tried creating separate APIs in Spark (the original RDD API did it this way, with a package for Scala and another package for Java) and it was not great. Initially it was OK, but over time things diverge and functionalities are added to one without adding to the other. In addition, this creates a lot of burden on developers who create libraries on top of Spark. For example, the machine learning library on Spark had to choose between creating parallel APIs vs overloading every function twice.

**Comment by szeiger** [comment]
I'm also opposed to this for the reasons that have already been raised (incompatible API designs, non-implementable methods, discoverability, naming conflicts now and in the future). 

Additionally it would close the door for better specialization support. It would be great if we could eventually support unboxed iterators and unboxed operations on specialized collection types, either through `@specialized` or some future mechanism. Any generic way of achieving this would be incompatible with Java where you need manually specialized, incompatible types like `IntIterator`.

I like the idea that was brought up by @Ichoran:

> For return types, we could make first-class `asJava` methods on the collections to translate to the nearest Java version

While the new Scala API should be more Java-friendly out of the box, we could make it easier to use by having `toJava` methods and static `fromJava` methods directly in the collection types. We already have everything that is needed to support the conversions but they are not as convenient to use from Java. Of course, this needs to be weighed against modularization because it would add a dependency on some basic Java APIs to the core collection library.

**Comment by jroper** [comment]
@rxin I have very little experience with Spark so please take everything I say with a grain of salt, I can only really speak to my own experiences. We had similar difficulties in Play Framework with API functionalities diverging. This is particularly true for the Scala API gaining features that the Java API didn't have, which we found was due to a combination of all of the following:

* Due to Scala's expressiveness, many features could be added with minimal effort. But often the same feature in Java, to give the same level of functionality, had to have significantly more code, for example, where you can just use a partial function in Scala, a similar feature in Java might require having to store a map of classes to functions to handle things of that type.
* The majority of contributors tend to be Scala developers, who don't care about or what to write the Java API.

Our solution was to first be disciplined about this ourselves, and then to make extremely clear in the contributor guidelines that PRs would only be accepted if they included parity with both APIs. Sometimes it means rejecting a good contribution, but once we shifted the culture of the project and its contributors, we found it to not be too bad. I believe the Akka team even had some automated checking developed to ensure feature parity - not sure where they got to with this.

And I understand about the libraries on top - we of course have the same thing for all our libraries. Some things that can help here include having built in converters between types and APIs (a la toJava/toScala), this offers a middle ground for library maintainers that don't want to maintain libraries for both. But ultimately the people building libraries on top face the same problems that you do in their own APIs whether you provide a shared or separate API or not - it's very difficult to provide a great idiomatic developer experience for both languages with the same API.

Anyway, I might be derailing this topic a little.

**Comment by julienrf** [comment]
I’m also against having more coupling with the Java collections. IMHO the right way to improve Java support is to do it via https://github.com/scala/scala-java8-compat.
