### ISSUE TITLE
Experiment with performance of unboxed Options

### ISSUE THREAD

**Issue by nicolasstucki** [scala/collection-strawman#322]
Unboxed Options (or `UOption`) are a version of `Option` that do not require boxing for references that vas designed by @sjrd. These shift the cost of boxing references to boxing different levels of nesting of a `None` in a `Some`. This cost is mostly in runtime class checks when accessing the element or deconstructing the Option.

We are not sure if the performance is in fact better. But we avoid allocation of all `Some` objects (even nested ones) and to access the values we replace a memory indirection be an additional `isInstanceOf`. It feels like it should help.

It would be great if someone can replace all `Option`s by unboxed options and analyze the performance of such construct.

The latest version of the code of `UOption` can be found https://github.com/lampepfl/dotty/pull/3181

**Comment by shado23** [comment]
I just read about the approaching feature freeze for 2.13. I assume that means unboxed Options likely won't make it in? It would be great to have null-safety without the performance impact it currently has. Since the implementation has been battle tested in Scala.js for some time the risks should be manageable.

**Comment by sjrd** [comment]
> Since the implementation has been battle tested in Scala.js [...]

It hasn't. Scala.js uses the same `Option` as Scala/JVM.

**Comment by shado23** [comment]
> It hasn't. Scala.js uses the same Option as Scala/JVM.

Ah, my mistake. Thanks for clearing this up.

**Comment by SethTisue** [comment]
I suggest we just close this ticket as it isn't actually about collections. (And this entire repo is winding down anyway.)

**Comment by nicolasstucki** [comment]
Yes, we should close it. This is not the place for this experiment anymore.

**Comment by shado23** [comment]
Is there another open ticket that replaces this to keep track of this? Otherwise it seems premature to me to just close it.

**Comment by szeiger** [comment]
There doesn't seem to be a ticket on https://github.com/scala/bug/issues. I suggest opening one there if we want to track this for Scala but since this is being experimented with in Dotty I don't think we'd do anything about it in the remaining Scala 2.x releases until this feature gets merged into Dotty.

**Comment by nicolasstucki** [comment]
Currently there is no one working on it in Dotty.
