### ISSUE TITLE
Improve usability of lengthCompare

### ISSUE THREAD

**Issue by joroKr21** [scala/collection-strawman#338]
In most codebases I've seen people just use `seq.length/size <> n` even though `seq.lengthCompare(n) <> 0` is recommended for sequential collections. In some cases it's probably for lack of knowledge, but in others the latter is just deemed too unreadable. 

My suggestion is to add some shortcuts that make it more pleasant to use.
Something along those lines:
```scala
def lengthEq(n: Int):  Boolean = lengthCompare(n) == 0
def lengthMin(n: Int): Boolean = lengthCompare(n) >= 0
def lengthMax(n: Int): Boolean = lengthCompare(n) <= 0
```

Other suggestions also welcome, of course.

This particular issue came up on Gitter.

**Comment by joroKr21** [comment]
Link to chat: https://gitter.im/scala/collection-strawman?at=5a55f0fcd0514c785b120ece

**Comment by SethTisue** [comment]
maybe `lengthIs`, `lengthAtLeast`, `lengthAtMost`

**Comment by sjrd** [comment]
`length_==`, `length_>=`, `length_<=`

**Comment by jtjeferreira** [comment]
what about adding `seq.lengthCompare(anotherSeq): Int`

**Comment by isaias-b** [comment]
What about this kind of interface? 
```scala
  implicit class SeqLikeOps[+A, +Repr](s: SeqLike[A, Repr]) {
    object lazyLengh {
      def <(value:  Int) = s.lengthCompare(value) < 0
      def >(value:  Int) = s.lengthCompare(value) > 0
      def ==(value:  Int) = s.lengthCompare(value) == 0
      def <=(value:  Int) = s.lengthCompare(value) <= 0
      def >=(value:  Int) = s.lengthCompare(value) >= 0
    }
  }
```

That allows to use:
```scala
val s: Seq[String] = ???
s.lazyLength < 10
s.lazyLength == 10
s.lazyLength > 10
```

However, i am not a DSL expert maybe this can be implemented without an extra inner `object`?

**Comment by joroKr21** [comment]
No, but the usability is almost the same (modulo `_`)
> Oh is this suggestion doing the exact kind of thing? sweat_smile #338 (comment)

**Comment by aleks-sidorenko** [comment]
`lengthEquals, lengthMoreThan, lengthLessThan`

**Comment by NthPortal** [comment]
Are most people happy (or at least okay) with Sébastien's suggestion?

**Comment by SethTisue** [comment]
I like Sébastien's suggestion best.

**Comment by mhalttu** [comment]
I guess Sébastien is https://github.com/sjrd and his suggestion is
>`length_==, length_>=, length_<=`

I personally find that syntax a bit ugly. In my opinion we should avoid partially symbolic method names. Do we have examples of similar style elsewhere in the project?

I preferred aleks-sidorenko's `lengthEquals, lengthMoreThan, lengthLessThan` because it captures the same idea but looks cleaner (albeit slightly more verbose). 

There is some elegance in isaias-b's suggestion too, but I think there is benefit with the fact all the methods related to `lengthCompare` start with the `length` prefix.

**Comment by NthPortal** [comment]
I have actually thought of a way to do @isaias-b's suggestion without having to allocate an object.

```scala
trait SeqOps[+A, +CC[_], +C] extends Any
  with IterableOps[A, CC, C] { self =>
  /* ... */

  // open to bikeshedding this name
  def lengthCompare: SeqOps.LengthCompareOps[A, CC, C] = new LengthCompareOps(this)
}

object SeqOps {
  // open to bikeshedding the equals and not equals methods
  final class LengthCompareOps[A, CC[_], C, S <: SeqOps[A, CC, C]] private(val seq: S) extends AnyVal {
    def <(len: Int): Int = seq.lengthCompare(len) < 0
    def <=(len: Int): Int = seq.lengthCompare(len) <= 0
    def ===(len: Int): Int = seq.lengthCompare(len) == 0
    def =!=(len: Int): Int = seq.lengthCompare(len) != 0
    def >=(len: Int): Int = seq.lengthCompare(len) >= 0
    def >(len: Int): Int = seq.lengthCompare(len) > 0
  }
}
```

Thoughts?

**Comment by mhalttu** [comment]
How often do you need `lengthCompare(n) >= 0` or `lengthCompare(n) <= 0`? I would imagine `lengthCompare(n) == 0` is by far the most common use case.

How about simply implementing `lengthEquals` method for now?

**Comment by Ichoran** [comment]
I like symbols more than practically everyone (I always use `/:` for instance), but the alphanumeric-symbolic hybrid suggested here seems really unfriendly to me.

I think `lengthAtLeast` and `lengthAtMost` work slightly better than `lengthLessThan` and `lengthMoreThan` because of overflow (`lengthLessThan(n+1)` is bad news when `n` is `Int.MaxValue`).

The other option to consider is `takeLength(n: Int): Int` which returns the exact length unless the length is `n` or more, at which point it stops at `n`.

**Comment by sjrd** [comment]
> Do we have examples of similar style elsewhere in the project?

We have `List.reverse_:::`, which is named as such because `xs reverse_::: ys` is semantically equivalent to `xs.reverse ::: ys`, but faster.

Likewise, `xs length_> 2` would be semantically equivalent to `xs.length > 2`, but faster.

So we have a very very close precedent for my suggestion.

**Comment by Ichoran** [comment]
`reverse_:::` is only named as such to get right-to-left evaluation, isn't it?

**Comment by sjrd** [comment]
No that's not necessary. It could have been called `reverseAndPreprendTo` and the implementation would just have swapped `this` and `that`.
