### ISSUE TITLE
more precisise type for Option.zip

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/collection-strawman#38]
Some(1).zip(Some(2)) // List((1, 2)): Iterable[(Int, Int)]

Option[(Int, Int)] would make more sense.

**Comment by SethTisue** [comment]
it's https://issues.scala-lang.org/browse/SI-8394; see https://github.com/scala/scala/pull/4836

**Comment by julienrf** [comment]
I think we can close this one because of scala/scala#4836.

**Comment by tkroman** [comment]
@julienrf what about helper methods in the companion? Analogous to `Future.sequence/fold/traverse`. If there was a bunch of these defined for `Option`, there would also be a benefit of avoiding to-iterable conversion in some cases.

**Comment by julienrf** [comment]
> what about helper methods in the companion?

I’m not sure to understand what you want. Do you want `Future.sequence` to also work for `Option[Future[_]]`? Or do you want an `Option.sequence` method that would turn a `C[Option[A]]` into an `Option[C[A]]` for any collection `C`?

Anyway, both would be super useful ;)

But I’m afraid this would go beyond the scope of the work on the collections.

I think we should define `Future.sequence` in terms of a `Traverse` typeclass, so that it would work with `Option[Future[_]]` or `Either[_, Future[_]]` in addition to `C[Future[_]]` (for any type `C[A] <: Iterable[A]`).

And we should also define it in terms of a `Zippable` typeclass (defining a `zipWith` method), so that it would work with `C[Option[_]]` in addition to `C[Future[_]]`.

**Comment by tkroman** [comment]
I meant the latter, e.g. `Option.sequence`, `Option.zip` (also, extend that to more than 2 args - maybe something similar to what `CartesianBuilder` allows to do in cats) etc.

For doing `G[M[_]] => M[G[_]]` we have monad transformers, so I'm not sure if bringing something that generic into stdlib is a good idea (when I think about this, I remember how passionate people were about not bringing a JSON implementation into stdlib, too).

So my proposal was much more narrow - just dump things that are potentially breaking into companion so we both don't break anything _and_ have a benefit of them being present in some form or another.
