### ISSUE TITLE
Consider adding sortInPlace to mutable collections

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#471]

**Comment by Ichoran** [comment]
On `Seq` only, obviously.  It doesn't really have sensible performance characteristics on `LinearSeq` but last I checked we don't have that any more.  So just `mutable.Seq` or `mutable.IndexedSeq`.  The key is that you need to have a fast swap operation.  (Otherwise you are rebuilding two new collections: a new sorted collection, and yourself again, now sorted.)

**Comment by kamilkloch** [comment]
I will give it a try.

**Comment by erikerlandson** [comment]
What is the contract for this? Provided for any subclass that allows sub-linear sorting, without constructing a copy?  For example a linked list can be sorted in sublinear time using merge sort, but can it be done without creating a copy of the input?

**Comment by kamilkloch** [comment]
@erikerlandson What do you mean by sublinear time for sorting?
For me, sortInPlace make sense only for collections with fast rndom access, in our case `IndexedSeq`. What do you think?

**Comment by erikerlandson** [comment]
@kamilkloch I mis-spoke there, but basically "not greater than n-log-n cost" was what I was getting at.

@Ichoran mentioned "mutable.Seq or mutable.IndexedSeq" above - and maybe I am reading too much into it but mutable.Seq includes ListBuffer, which you _could_ sort with merge sort in n-log-n time, but it might involve copying original nodes, like `mapInPlace` appears to do.

So there are possible policies. "Only available if cost is not greater than n-log-n" or "only available if objects are not being allocated to do it".  Maybe these were already documented?

**Comment by NthPortal** [comment]
Since sorting in place doesn't make sense for a lot of (most?) `mutable.Seq` implementations, where is the method defined? On all `mutable.Seq`s, and it's documented as just a best-effort thing? Or only on particular implementations for which it makes sense?

If we follow Java's strategy (copy to an array, sort the array, and copy back), it could have a reasonable default implementation for most/all `mutable.Seq`s. However, calling it "in place" is a bit misleading. While it doesn't allocate a new collection of its own type, it *does* allocate an array of its size (also, `j.u.Arrays.sort` may consume significant memory).

**Comment by kamilkloch** [comment]
Assumption: we do not intend to reimplement sorting, but rather rely on its implementation in Java. 

Then: sorting in place (in my understading = without any allocations) is possible only for mutable collecttions which are backed by `scala.Array`, i.e.
 * `mutable.ArrayBuffer`
 * `ArrayDeque`
 * `ArraySeq`

In all 3 cases, `scala.Array` is internalized in the respecitve classes. 

How do we want to proceed?

**Comment by erikerlandson** [comment]
I think providing it for array backed classes is a reasonable start. It's better to decide policy on other classes later, than provide them and regret it.

OT, if "in place" is "no allocations" I do wonder about `mapInPlace` for `ListBuffer`

**Comment by NthPortal** [comment]
`java.util.Arrays.sort` is [not in-place](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#sort-T:A-java.util.Comparator-):

>Temporary storage requirements vary from a small constant for nearly sorted input arrays to n/2 object references for randomly ordered input arrays.

**Comment by NthPortal** [comment]
I think `sort` (similar to Java's [`List.sort`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#sort-java.util.Comparator-)) would be a better name, but I'm concerned about confusion between it and `sorted`.

**Comment by julienrf** [comment]
Also, I think it would make sense to have it on `mutable.Seq` as well: we could use a merge sort on `LinearSeq`.

**Comment by kamilkloch** [comment]
@julienrf Please take a look.
