### ISSUE TITLE
`seq` operation has been removed

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#554]
It was used to convert a `GenXxx` into a sequential collection. New collections are only sequential, so there is no need for this method, but we should keep it and deprecate it (implementation would just return `this`).

**Comment by julienrf** [comment]
Other methods that could have the same treatment: `fold`, `reduce` and `scan`.

**Comment by julienrf** [comment]
We should also implement a rewrite rule that transforms `fold` calls to `foldLeft`, etc.

**Comment by szeiger** [comment]
The best return type for `seq` would be `C` or `this.type`, making for a very simple implementation in a single place. This doesn't cover `StringOps` though. `"foo".seq` is supposed to return a collection type (so no `C` because that would be `String`) and we don't want `StringOps` to leak into return types (so no `this.type` either).
