### ISSUE TITLE
Opt-In to partial methods on collections

### ISSUE THREAD

**Issue by ShaneDelmore** [scala/collection-strawman#72]
I would like to propose we consider making unsafe collections operations opt-in. I understand the case for using them when you need performance, have reason to believe they will be safe, or plan on handling the error so this is not a suggestion to remove them, just to make them opt-in.

@Ichoran has suggested a possible implementation through requiring the import of a NonTotal token to use the unsafe methods.

If this proposal is accepted I would be happy to do the work related to it as well as write a scalafix rewrite to add the imported NonTotal token where required to maintain backwards compatibility.  With a nice message stating that the user needs to import scala.collection.NonTotal (or Partial?) it would be low overhead for users but still give a reminder to those new to deciding when it is acceptable to use the partial methods in collections.

**Comment by tpolecat** [comment]
What's the argument for not making all these methods return `Option`? Is it just the cost of constructing the `Option`? Seems like a lot of complexity to absorb just to avoid that case.

**Comment by ShaneDelmore** [comment]
The argument is that the option of only having Total methods has been discussed and rejected already, so this is an attempt to see if we can still make a safety improvement without forcing a style of coding on people who like the current partial methods.  

I felt this might have a higher chance of gaining traction as it is in line with other things we already use in Scala to remind people to think twice before using a feature such as importing a language feature or enabling compiler warnings.

**Comment by pathikrit** [comment]
We can also overload them e.g.

```scala
class Seq[A] {
  // we should use this one
  def min(implicit ev: Ordering[A]): Option[A]

  // easy to switch to this one for current users
  def min(whenEmpty: => A = {throw new NoSuchElementException()})(implicit ev: Ordering[A]): A  =
    min(ev).getOrElse(whenNonEmpty)
}
```

**Comment by tpolecat** [comment]
How's about we rename all the unsafe methods? `max` → `unsafeMax`, `reduce` → `unsafeReduce`, etc. and then make the primary ones safe? You still have the fast ones for all the ninja rockstars.

**Comment by nafg** [comment]
@tpolecat as long we don't take it as far is Lift did https://github.com/lift/framework/blob/master/core/common/src/main/scala/net/liftweb/common/Box.scala#L399-L431 ;)

**Comment by nafg** [comment]
If we had an unboxed option type (like scalajs js.UndefOr) would that solve the performance issue? Or is the idea to avoid performing safety checks?

**Comment by odersky** [comment]
This sounds a bit like what we have in mind for an effect system, with NonTotal being an effect. I think it's too ambitious for the current rewrite though. We need to experiment first with effect systems and then decide whether this should be part of the compiler, a linter, or be dropped.

**Comment by ShaneDelmore** [comment]
@odersky Given that you feel it is too soon to have these methods opt-in, should we back down to the smaller unsafe renaming @tpolecat proposed?

**Comment by Ichoran** [comment]
@ShaneDelmore - That is ramping up, not backing down.  Renaming with a lot of `unsafeX` in place of `x` is a bigger change from the perspective of a user.

**Comment by ShaneDelmore** [comment]
Any other ideas or should I consider this rejected/postponed and close the issue?  No specific rush on my end other than not wanting to leave an open issue hanging around. Also I will be going offline for several days any minute now so if alternatives are proposed I will follow up on them sometime next week.

**Comment by Blaisorblade** [comment]
@Ichoran 
> Renaming with a lot of unsafeX in place of x is a bigger change from the perspective of a user.

Yes, but renaming *and* providing a scalafix refactoring has less impact, and they're easier than an effect system.

Worst-case, we could also just add `safeX` methods, like Haskellers did. Yes, that doesn't make unsafe methods opt-in, but it seems easier and less controversial.
Adding `safeX` methods and *then* renaming `x` to `unsafeX` would be a bit silly, so we just need to pick one.

**Comment by Blaisorblade** [comment]
> If we had an unboxed option type (like scalajs js.UndefOr) would that solve the performance issue?

Unboxed options would be enough IMHO, but they aren't planned in 2.13.
Could collections provide Scala.JS-only methods internally? Right now they'd have to be added via implicit classes I guess?

> Or is the idea to avoid performing safety checks?

Only Scala Native could avoid needed safety checks, and they still lack `@unsafe` (https://github.com/scala-native/scala-native/issues/44).

**Comment by Ichoran** [comment]
@Blaisorblade - scalafix only fixes code, not mental representations of how to code or what it means.  The impact is still considerably greater.  Opt-in warnings do not require any changes to mental representations until requested.

Also, it is not necessary to have "an effect system".  You just need an optional warning system and have things annotated by hand.  Having an effect system and other methods of propagation of information would be great, but it's not necessary.

**Comment by Blaisorblade** [comment]
@ShaneDelmore forgot to tag you on `safeX` methods above — WDYT? That's the most conservative proposal.

On the other hand, it's not clear what API you proposed originally for, say, `head`, because @Ichoran suggested the converse. Are you proposing as API `def head(implicit nt: NonTotal): A`, where the implicit value for `NonTotal` has to be imported explicitly?

@Ichoran:

> scalafix only fixes code, not mental representations of how to code or what it means. The impact is still considerably greater.

Agreed on that.

> Opt-in warnings do not require any changes to mental representations until requested.

But in @ShaneDelmore's proposal, you opt-in to enable `head`—it's not "opt-in warnings", that would take a WartRemover-like tool. What do you have in mind?

> Also, it is not necessary to have "an effect system". You just need an optional warning system and have things annotated by hand. Having an effect system and other methods of propagation of information would be great, but it's not necessary.

To me, "Optional warning system" can mean a million things, and all of them could be effect systems (however rudimentary). A `NonTotal` token, in particular, is exactly an effect system (see below). IMHO we're flying so high we can't see tradeoffs, much less discuss them...

IIUC, you're aiming for something easy to implement, while Odersky worries more about annotation/migration overhead.

To clarify, Odersky brought up "effect system" because your idea of a "NonTotal" token resembles the effect system in the works for Dotty:

> @Ichoran has suggested a possible implementation through requiring the import of a NonTotal token to use the unsafe methods.

To clarify the sort of effect system under discussion, here's how it could look like based on https://www.slideshare.net/Odersky/scala-days-san-francisco-45917092/45 and related discussions:

```
type NonTotal = CanThrow[EmptyException] //strawman
type NonTotalR[A] = implicit NonTotal => A
class List[A] {
  def head: NonTotalR[A]
  ...
}
def f(l: List[A]): NonTotalR[A] = {
  l.head //works
}
def g(l: List[A]): A = {
  l.head // fails or warns
}
```

That can also support an `import foo.bar.NonTotal` to enable the capability globally in a file, if you want (much like SIP-18 imports of implicits).
But lots of questions on migration (how to opt-in/opt-out so that overhead is limited) are still open.

**Comment by tpolecat** [comment]
@Blaisorblade re: `safeFoo` there is a principle in linguistics called *markedness* which basically means less-common cases are more syntactically elaborate than the common case. I think this applies to API design as well. As we certainly wish users to default to the safe case I think `foo`/`unsafeFoo` is a preferable convention. Since there's already a rewrite tool in the mix I would hope there wouldn't be a substantial difference in effort.

**Comment by Blaisorblade** [comment]
@tpolecat 

If we started from scratch, I'd more easily pick the `unsafe` convention of the two.

> As we _certainly_ wish users to default to the safe case I think foo/unsafeFoo is a preferable convention.

For myself as a user, I 100% agree. Things are less clear for the entire community.
(And luckily, it's not my judgement call here).

> Since there's already a rewrite tool in the mix I would hope there wouldn't be a substantial difference in effort.

Yes, but scalafix doesn't rewrite user heads—as @Ichoran mentioned. I'm not sure if that's a big concern—I can argue both ways since there's no data in sight.

Sadly, it's hard to quantify tradeoffs on developer effort—there's lots of research on Scalafix-like tools, but little on cognitive overhead.
https://scholar.google.com/scholar?hl=en&q=api+migration+with+refactoring+tools

More concretely: do we have big or small success stories on scalafix, before we use it on core Scala libraries?

Back to technical arguments: while I like assuming a sufficiently smart compiler and caring about safety (or just ignoring low-level performance issues), we know that Scala doesn't have a sufficiently smart compiler — we still need things like https://github.com/scala/scala/pull/5785/commits/dbefe29463bf257e2d70155ef87c20fa8b13dbfa, which makes me sad. If `ArrayList[A].head` returns `Option[A]`, it'd take even stronger optimizations to remove the overhead.

BTW, which methods do you target? Nobody mentioned `apply` — it's a special name, but `safeApply` and `unsafeApply` aren't.

**Comment by tpolecat** [comment]
> Yes, but scalafix doesn't rewrite user heads 

Users would have to rewrite their own heads. The typechecker will help.

> BTW, which methods do you target? Nobody mentioned `apply`

Any method that may fail to yield an answer under normal usage, like `head`, `tail`, `reduce`, `max`, etc. is fair game. `apply` comes from `PartialFunction`, which is a different and potentially more important design discussion since it also begs a discussion of partial pattern-matching.

Anyway that's all I'm going to say about this. You understand my point.

**Comment by Ichoran** [comment]
@Blaisorblade  - You could do it with implicits the way you show above, but only if it's actually made to have zero runtime overhead (including no traces in the bytecode that might interfere with overrides that are in fact total).  This seems unlikely to be achieved in 2.13.  But adding a `scala.language._`-like warning system ought to be more feasible.  (Note that you don't need to add a PostfixOps implicit to postfix methods.)

I would want you to be able to easily opt in any direction: no implicit, a deprecated implicit, or a fully okay implicit.  With careful namespacing you should be able to shadow each of these to get the behavior you want in any particular context.  This means that any project is at most a top-level import per file away from recovering the original behavior without warnings.

A linter solution would be fine also, but the linter would need help in the code or it will get out of sync and be of limited utility.  So it has to be able to read _something_, even if it is only a ScalaDoc comment.

The difference between all of these things and an effect system is that the effect system could have the compiler help you propagate these warnings.  Here, you'd be on your own.  I'm all for compiler help!  I just think it might be too hard to get to and prevent an intermediate solution from being deployed that could help people who would like help without causing grief for those who are okay with things as they are.  This system could then be dropped in favor of the effect system version once/if the latter is ready.

**Comment by szeiger** [comment]
I find the idea of making language imports extensible by libraries the most promising one so far. It would enable easy migration, be completely optional, and have no runtime overhead. It should be much simpler to spec than an effect system but it still requires some compiler support, so we'd have to get it into the 2.13 compiler.

**Comment by Blaisorblade** [comment]
> @Blaisorblade - You could do it with implicits the way you show above, but only if it's actually made to have zero runtime overhead (including no traces in the bytecode that might interfere with overrides that are in fact total). This seems unlikely to be achieved in 2.13.

I agree that's not for 2.13—it's ongoing Dotty work. Let's just be aware that's the eventual goal.

> I find the idea of making language imports extensible by libraries the most promising one so far.

How does the compiler know which methods are unsafe? +1 to extensible, so I'd assume they'd be marked by a new annotation `@scala.annotation.requiresLanguageToken(scala.collection.NonTotal)`?

> This system could then be dropped in favor of the effect system version once/if the latter is ready.

That takes some planning, but it seems the client side could be made compatible.

However, I just realized a global capability `scala.collection.NonTotal` would probably have to be dropped in Dotty for a sound capability-based effect system. Still, maybe the client code can still be handled by a new scalafix rewrite.

**Comment by ShaneDelmore** [comment]
I think all of the discussion that is going to happen on this issue may have already happened.  What is the next step?  Should I just create separate messages for each option and let people thumbs up their preferred solution (including the option to do nothing at all)?

**Comment by julienrf** [comment]
Hey Shane, I’m sorry for the delay.

I think you raised very relevant points. We discussed the issue with @odersky and @szeiger and our conclusion was that the best solution would be to have some support for effects or capabilities like in the solution described in @Blaisorblade’s [comment](https://github.com/scala/collection-strawman/issues/72#issuecomment-299680236). However, we prefer to wait for having proper support for effects in the language rather than designing a poor man’s solution (e.g. based on an implicit parameters). Consequently we will not address these issues in the current redesign.
