### ISSUE TITLE
Make zipWithIndex return a `View[(A, Int)]`

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#89]
What do you think of making `zipWithIndex` return a `View[(A, Int)]`?

**Comment by odersky** [comment]
I don't think this is a good idea. If you have both strict and lazy collections, it's very important to have a clear picture what returns what. Ideally, only `.view` returns a lazy collection. We currently violate that principle with `mapValues` and some other map-related functions. That's not good, people get confused. Maybe there's no way around `mapValues`. But we should not make the problem bigger.

**Comment by julienrf** [comment]
OK, so users would just write `.view.zipWithIndex`

**Comment by odersky** [comment]
Yes, exactly.

**Comment by szeiger** [comment]
I agree. I did this as a micro-optimization in https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/ConstArray.scala because it's the only kind of `zipWithIndex` we needed (which is probably true in general for immutable collections) but for a general-purpose library I don't think it's worth the inconsistency. Plus, a copying `zipWithIndex` could be useful for mutable collections.
